import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import SearchInput from '../components/SearchInput'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'


export default function Home() {
	const [searchTerm, setSearchTerm] = useState('')
	const handleSearch = (e) => setSearchTerm(e.target.value)

	const router = useRouter()

	const handleSubmit = (e) => {
		e.preventDefault()
		
		if(searchTerm) {
			router.push(`/search?q=${searchTerm}`)
		} else {
			alert('Please input text whatever you want')
		}
	}

	return (
    	<div>
			<Head>
				<title>Goolok</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>	
			<Header/>
			<form className="flex items-center justify-center flex-col mt-32 px-7">
				<h1 className="text-6xl md:text-8xl font-bold mb-5">
					<span className="text-blue-400">G</span>
					<span className="text-red-400">o</span>
					<span className="text-yellow-400">o</span>
					<span className="text-blue-400">l</span>
					<span className="text-green-400">o</span>
					<span className="text-red-400">k</span>
				</h1>
				<SearchInput value={searchTerm} handleChange={handleSearch}/>
				<div className="flex items-center mt-5 space-x-2">
					<button className="btn" onClick={handleSubmit}>Goolok Search</button>
					<p className="btn">I'm Feeling Lucky</p>
				</div>
				<Footer/>
			</form>
    	</div>
  )
}


