import React from 'react'
import Head from 'next/head'
import ResultHeader from '../components/ResultHeader'
import ResultContent from '../components/ResultContent'

const Search = ({results}) => {

    return (
        <div>
            <Head>
				<title>Search Result</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>	
            <ResultHeader />
            {/* {results.error ? (
                <div className="grid place-items-center mt-20">
                    <h1>Ooops, Maaf request sudah habis :(</h1>
                </div>
            ) : (
                <ResultContent results={results}/>
            )} */}
            <ResultContent results={results}/>
        </div>
    )
}

export default Search


export const getServerSideProps = async (context) => {

    const term = context.query.q
    const pageIdx = context?.query?.pageIdx || 0
    
	const res = await fetch(`https://www.googleapis.com/customsearch/v1?key=AIzaSyA2xoxtq1Xpq5VWZ3QlWwyRvz_R93FEnO8&cx=42a691f53d3ecd66b&q=${term}&start=${pageIdx}`)
    const data = await res.json()

    return {
        props: {
            results: data
        }
    }
}

